### ISSUE TITLE
Sobre a seção 3

### ISSUE THREAD

**Issue by angelorocha** [HIAE/wp-test#1]
**Desenvolver 3 CPT plugins para:**

1.     gerenciar o banner no Header inclusive os textos;
2.     gerenciar as redes sociais no topo e no footer;

Sobre esses dois itens, o interessante seria utilizar o recurso de "theme option page/register option", pois o uso de CPT (Custom post type) para gerenciar configuração de layout não é muito usual. Posso prosseguir dessa forma? O restante das specs estão entendidas.

**Comment by adhenrique** [comment]
Fala @angelorocha tudo tranquilo?

Ok, vc pode prosseguir dessa forma. A idéia aqui, é analisar seu ponto de vista e seu código.

**Comment by adhenrique** [comment]
Aliás, obrigado por pontuar esse detalhe. Vou ajustar o README.

**Comment by angelorocha** [comment]
Obrigado!
