### ISSUE TITLE
Dúvida sobre fontes

### ISSUE THREAD

**Issue by edersilva** [HIAE/wp-test#2]
Quais foram as fontes usadas no desenvolvimento do layout? Ou posso usar alguma outra? 
Obrigado.

**Comment by adhenrique** [comment]
Fala Eder boa tarde.

A tipografia é a família Open Sans.

Att,

Em sáb, 8 de ago de 2020 13:44, Eder Silva <notifications@github.com>
escreveu:

**Comment by edersilva** [comment]
Obrigado @adhenrique
